# php:7.2-fpm + mysql:5.7 + nginx:latest + redis:latest
version: "3" #版本
services:  #开启的容器服务 
  nginx:  #服务名
    image: nginx  #使用镜像（先从本地查看，若没有则从仓库获取）
    restart: always #是否启动容器是重启
    depends_on:
    - php
    ports: #映射端口号
    - "80:80"
    - "443:443"
    container_name: docker-nginx
    volumes: #挂载文件   宿主机文件：容器文件
    - /Users/wu/www/Docker-my/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - /Users/wu/www/Docker-my/nginx/sites-conf:/etc/nginx/sites-conf:ro
    - /Users/wu/www/Docker-my/nginx/ssl:/etc/nginx/ssl:ro
    - /Users/wu/www/Docker-my/nginx/logs:/logs
    - /Users/wu/www/Docker-my/code:/var/www
    networks: #网络
      app_net: #网络名称
        ipv4_address: 192.168.0.1 #设置容器的内部ip
    environment: #环境配置
    - TZ=Asia/Shanghai #设置时区
  php:
    image: php-pdo-redis:7.2-fpm
    restart: always
    ports:
    - "9000:9000"
    container_name: docker-php
    volumes:
    - /Users/wu/www/Docker-my/code:/var/www
    networks:
      app_net:
        ipv4_address: 192.168.0.2
  mysql:
    image: mysql:5.7
    restart: always
    ports:
    - "3306:3306"
    container_name: docker-mysql
    volumes:
    - /Users/wu/www/Docker-my/mysql/data:/var/lib/mysql
    - /Users/wu/www/Docker-my/mysql/my.cnf:/etc/mysql/my.cnf
    - /Users/wu/www/Docker-my/mysql/logs:/logs
    networks:
      app_net:
        ipv4_address: 192.168.0.3
    environment:
    - TZ=Asia/Shanghai
    - MYSQL_ROOT_PASSWORD=123456
  redis:
    image: redis
    restart: always
    ports:
    - "6379:6379"
    container_name: docker-redis
    volumes:
    - /Users/wu/www/Docker-my/redis/redis.conf:/etc/redis.conf
    - /Users/wu/www/Docker-my/redis/data:/usr/local/redis/data
    - /Users/wu/www/Docker-my/redis/redis.log:/usr/local/redis/redis.log
    command: redis-server /etc/redis.conf
    networks:
      app_net:
        ipv4_address: 192.168.0.4
    environment:
    - TZ=Asia/Shanghai
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.0.0/16 #网段 必须是未使用的网段
