# php:7.2-fpm + mysql:5.7 + nginx:latest + redis:latest
version: "3" #版本
services:  #开启的容器服务 
  nginx:  #服务名
    image: nginx  #使用镜像（先从本地查看，若没有则从仓库获取）
    restart: always #是否启动容器是重启
    ports: #映射端口号
      - "80:80"
      - "443:443"
    volumes: #挂载文件   宿主机文件：容器文件
      - /Users/wu/www/Docker-my/code:/var/www/html/test
      - /Users/wu/www/Docker-my/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks: #网络
      app_net: #网络名称
        ipv4_address: 192.168.0.1 #设置容器的内部ip
    environment: #环境配置
      - TZ=Asia/Shanghai
  php:
    image: php-pdo-redis:7.2-fpm
    ports:
     - "9000:9000" 
    volumes: 
     - /Users/wu/www/Docker-my/code:/var/www/html/test
    networks:
      app_net:
        ipv4_address: 192.168.0.2
  redis:
    image: redis
    ports: 
     - "6379:6379"
    networks:
      app_net:
        ipv4_address: 192.168.0.4
    environment:
     - TZ=Asia/Shanghai
  mysql:
    image: mysql:5.7
    ports:
     - "3306:3306"
    volumes:
     - /Users/wu/www/Docker-my/mysql/data:/var/lib/mysql       
    networks:
      app_net:
        ipv4_address: 192.168.0.3
    environment:
     - TZ=Asia/Shanghai
     - MYSQL_ROOT_PASSWORD=123456
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.0.0/16 #网段 必须是未使用的网段
