#  nginx:1.17.2 + mysql:5.7.27 + php:7.3.8-fpm + redis:5.0.5
###redis的最新版本是5.0.2，redis镜像最新的版本是5.0.5
#  docker pull nginx:1.17.2
#  docker pull mysql:5.7.27
#  docker pull php:7.3.8-fpm
#  docker pull redis:5.0.5
#
#  cd nginx && docker build -t nginx:1.17.2-build .
#  cd mysql && docker build -t mysql:5.7.27-build .
#  cd php && docker build -t php:7.3.8-fpm-build .
#  cd redis && docker build -t redis:5.0.5-build .
#  docker-compose up

version: "3.2"

services:
  nginx:
#    build: ./nginx
    image: nginx:1.17.2-build
    depends_on:
    - php
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./www:/www
    - /Users/wu/www:/wwwroot
    # ssl的证书耶放在conf.d里吧
    - ./nginx/conf.d:/etc/nginx/conf.d
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx/logs:/logs
    networks:
      mylnmp_net:
        ipv4_address: 192.170.1.11
    extra_hosts:
    - "test.do:127.0.0.1"
    - "laravel.do:127.0.0.1"
    - "lumen.do:127.0.0.1"
    - "yii2-basic.do:127.0.0.1"
    - "yii2-advanced.do:127.0.0.1"
    - "xxnapi.do:127.0.0.1"
    - "xxnadmin.do:127.0.0.1"
    restart: always
    container_name: mylnmp-nginx
    privileged: true
    environment:
    - TZ=Asia/Shanghai

  php:
#    build: ./php
    # pecl install 构建的
    image: php:7.3.8-fpm-build
    # 源码包构建的
#    image: php:7.3.8-fpm-build-2
    ports:
    - "9000:9000"
    volumes:
    - ./www:/www
    - /Users/wu/www:/wwwroot
    - ./php/config/php.ini:/usr/local/etc/php/php.ini
    - ./php/config/php-fpm.conf:/usr/local/etc/php-fpm.conf
    - ./php/config/php-fpm.d:/usr/local/etc/php-fpm.d
    networks:
      mylnmp_net:
        ipv4_address: 192.170.1.12
    restart: always
    container_name: mylnmp-php
    privileged: true
    environment:
    - TZ=Asia/Shanghai

  mysql:
#    build: ./mysql
    image: mysql:5.7.27-build
    ports:
    - "3306:3306"
    volumes:
    - ./mysql/data:/var/lib/mysql
    - ./mysql/my.cnf:/etc/my.cnf
    - ./mysql/logs:/logs
    environment:
    - TZ=Asia/Shanghai
    - MYSQL_ROOT_PASSWORD=123456
    # 创建一个用户，初始化一下mysql
    - MYSQL_USER=root
    - MYSQL_PASSWORD=123qwe
    networks:
      mylnmp_net:
        ipv4_address: 192.170.1.13
    restart: always
    container_name: mylnmp-mysql
    privileged: true

  redis:
#    build: ./redis
    image: redis:5.0.5
    ports:
    - "6379:6379"
    volumes:
    - ./redis/redis.conf/:/usr/local/etc/redis.conf
    - ./redis/data:/usr/local/redis/data
    - ./redis/redis.log:/usr/local/redis/redis.log
    command: redis-server /usr/local/etc/redis.conf
    networks:
      mylnmp_net:
        ipv4_address: 192.170.1.14
    restart: always
    container_name: mylnmp-redis
    privileged: true
    environment:
    - TZ=Asia/Shanghai

networks:
  mylnmp_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.170.1.1/16
