#  以前的仅供参考
#  以后部署，和线上环境保持一致
#  
#
#  docker pull busybox:latest
#  docker pull nginx:latest
#  docker pull php:7.2-fpm
#  docker pull mysql:5.6
#  docker pull redis:latest
#
#  cd php && docker build -t php:7.2-fpm-build .
#
#  docker-compose up

version: '2'

services:
#  www:
#    image: busybox:latest
#    container_name: www
#    restart: always
#    privileged: true
#    tty: true
#    volumes:
#      - ./data:/data
#      - ../../testCode:/www/test
#    networks:
#      - lnmpv3_network
#    environment:
#      - TZ=Asia/Shanghai
#
#  nginx:
#    image: nginx:latest
#    container_name: nginx
#    restart: always
#    privileged: true
#    tty: true
#    depends_on:
#      - php
#    ports:
#      - 80:80
#      - 443:443
#    volumes:
#      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#      - ./nginx/ca/:/etc/nginx/ca
#      - ./nginx/log:/var/log/nginx/:rw
#    volumes_from:
#      - www
#    networks:
#      - lnmpv3_network
#    environment:
#      - TZ=Asia/Shanghai
#
#  php:
#    image: registry.cn-hangzhou.aliyuncs.com/soft_image/php:7.1.23-fpm
#    container_name: php
#    restart: always
#    privileged: true
#    ports:
#      - 9000:9000
#    depends_on:
##      - mysql
#      - redis
#    volumes:
#      - ./php/php.ini:/usr/local/etc/php/php.ini:ro
#      - ./php/php-fpm.conf:/usr/local/etc/php-fpm.conf
#      - ./php/php-fpm.d:/usr/local/etc/php-fpm.d
#      - ./php/conf.d:/usr/local/etc/php/conf.d
#      - ./php/log:/var/log/:rw
#      - ./mysql/mysqld:/dev/shm
#    volumes_from:
#      - www
#    networks:
#      - lnmpv3_network
#    environment:
#      - TZ=Asia/Shanghai
#
#  mysql:
#    image: mysql:5.6
#    container_name: mysql
#    restart: always
#    privileged: true
#    ports:
#      - 3306:3306
#    volumes:
#      - ./mysql/my.cnf:/etc/mysql/mysql.conf.d/my.cnf:ro
#      - ./mysql/data:/var/lib/mysql
#      - ./mysql/log:/var/lib/log
#      - ./mysql/mysqld:/var/run/mysqld
#    environment:
#      - MYSQL_ROOT_PASSWORD=root
#      # 创建一个用户，初始化一下mysql
#      - MYSQL_USER=root
#      - MYSQL_PASSWORD=root
#      - TZ=Asia/Shanghai
#    networks:
#      - lnmpv3_network
#
#  redis:
#    image: redis:latest
#    container_name: redis
#    restart: always
#    privileged: true
#    ports:
#      - 6379:6379
#    volumes:
#      - ./redis/redis.conf:/etc/redis/redis.conf:ro
#      - ./redis/db:/var/db
#      - ./redis/log:/var/log
#    command: redis-server /etc/redis/redis.conf
#    networks:
#      - lnmpv3_network
#    environment:
#      - TZ=Asia/Shanghai

  elasticsearch:
    image: elasticsearch:7.12.1
    container_name : elasticsearch
    restart: always
    privileged: true
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/logs:/usr/share/elasticsearch/logs
      - ./elasticsearch/plugins:/usr/share/elasticsearch/plugins
#      - ./elasticsearch/analysis:/usr/share/elasticsearch/config/analysis
    environment:
      - 'ES_JAVA_OPTS=-Xms256m -Xmx256m'
    networks:
      lnmpv3_network:
        ipv4_address: 192.181.1.16

  elasticsearch-head:
    image: mobz/elasticsearch-head:5
    container_name : elasticsearch-head
    restart: always
    privileged: true
    ports:
      - 9100:9100
    depends_on:
      - elasticsearch
    networks:
      lnmpv3_network:
        ipv4_address: 192.181.1.17

  kibana:
    image: kibana:7.12.1
    container_name : kibana
    restart: always
    privileged: true
    ports:
      - 5601:5601
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    depends_on:
      - elasticsearch
    networks:
      lnmpv3_network:
        ipv4_address: 192.181.1.18

networks:
  lnmpv3_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.181.1.1/24