FROM php:7.2-fpm
RUN apt-get update && apt-get install -y \
	libfreetype6-dev \
	libjpeg62-turbo-dev \
	libpng12*-dev \
	vim \
	curl \
	&& docker-php-ext-install pdo_mysql \
	&& docker-php-ext-install mysqli \
	&& docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
	&& docker-php-ext-install gd \
	&& curl -L -o /tmp/redis.tar.gz https://github.com/phpredis/phpredis/archive/3.1.3.tar.gz \
	&& cd /tmp \
	&& tar xfz /tmp/redis.tar.gz \
	&& mkdir -p /usr/src/php/ext \
	&& mv phpredis-3.1.3 /usr/src/php/ext/redis \
	&& docker-php-ext-install redis \